### ISSUE TITLE
cannot parse config.yml

### ISSUE THREAD

**Issue by EugenMayer** [manala/ansible-role-shorewall#1]
No matter what i do, even with an empty

```
manala_shorewall_config:
```

or this simple rule 
```
manala_shorewall_config:
  rules:
    - Access to SSH
    - { action: ACCEPT, source: net, dest: fw, proto: tcp, dest_port: 2201 }
```

i always get this error

```
 {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'None' has no attribute 'keys'\n\nThe error appears to have been in '/opt/boxen/homebrew/etc/ansible/roles/manala.shorewall/tasks/config.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: config > File\n  ^ here\n"}

```

I am using ansible 2.2 on osx

**Comment by hyvs** [comment]
Our readme was outdated, your simple rule should be :
```
manala_shorewall_configs:
  - file: rules
    config:
      # Access to SSH
      - ACCEPT: net fw tcp 2201 - -
```

`manala_shorewall_config` is now only used to configure directives in `/etc/shorewall/shorewall.conf`file
